kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "devopsodia.fullname" . }}
spec:
  host: imageidentificationroute-newdemo.apps.hpeopenshift.eastus.aroapp.io
  to:
    kind: Service
    name: {{ include "devopsodia.fullname" . }}
  port:
    targetPort: {{ .Values.service.port }}
