apiVersion: v1
kind: Service
metadata:
  name: {{ include "devopsodia.fullname" . }}
  labels:
    {{- include "devopsodia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: reactapp
  ports:
    - targetPort: 3000
      protocol: TCP
      port: 3000
